### ISSUE TITLE
Allow not showing up-down arrows in numeric 

### ISSUE THREAD

**Issue by BellLongworth** [facultyai/dash-bootstrap-components#1019]
Allow removing this:
![image](https://github.com/facultyai/dash-bootstrap-components/assets/63842998/3790186b-cbd9-447d-91bf-450ea10fbad1)

While keeping the features of the below:
dbc.Input(type='number', inputmode='numeric')

**Comment by tcbegley** [comment]
Hi @BellLongworth 

The number input is a standard HTML element that is rendered by your browser, so you need to use some CSS to customise how the browser renders it. Try the following taking from [this StackOverflow answer](https://stackoverflow.com/questions/3790935/can-i-hide-the-html5-number-input-s-spin-box)

```css
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

input[type='number'] {
  -moz-appearance: textfield; /* Firefox */
}
```

Put that in a CSS file in your `assets/` folder and it should do the trick.
