### ISSUE TITLE
dbc.Spinner() intial load lags on launch

### ISSUE THREAD

**Issue by marcstern14** [facultyai/dash-bootstrap-components#1026]
I have a multi-page dash app that uses a custom full screen spinner on launch. The idea is that in my app.py, I load in my data, and then once it's loaded, it goes to the landing.py page. The problem I'm having is that there is about a buffer between the app launch and when the spinner takes over, leaving a couple seconds of a white page with `Loading...` in the top left corner (which appears to be dash default font) before my much cooler spinner starts. Are there any recommendation around this issue? My basic set up on launch is below.

`app = DashProxy(
    __name__,
    external_stylesheets=external_stylesheets,
    suppress_callback_exceptions=True,
    use_pages=True,
    assets_folder=assets,
    pages_folder=pages,
    transforms=[ServersideOutputTransform()]
)

app.layout = html.Div(
    [
        page_container,
        dbc.Spinner(
            [
                dcc.Store(id='store', storage_type='session'),
                dcc.Store(id='store2', storage_type='session')
            ],
            spinner_class_name="mirror",
            type="grow",
            fullscreen=True,
            fullscreen_style={"background-color": "#000"},
            show_initially=True,
            spinner_style={
                "background-color": "rgba(0,0,0,0)",
                "font-size": "150%"
            }
        )
    ]
)`

**Comment by tcbegley** [comment]
Hi @marcstern14 

Check out [this topic](https://community.plotly.com/t/change-loading-to-a-spinner/52933/2) on the Plotly Forums.

The "Loading..." appears while the javascript bundles are being fetch and Dash is starting up, so the correct solution is to use some CSS that will be applied on initial page load. Updated and Bootstrap specific example below.

```python
import time

import dash_bootstrap_components as dbc
from dash import Dash


def slow_serve_layout():
    # this is just to slow down the initial load to make the spinner clear
    time.sleep(5)
    return dbc.Container(
        dbc.Alert("Hello, world!", color="success"), className="p-5"
    )


app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])
app.layout = slow_serve_layout

if __name__ == "__main__":
    app.run_server(debug=True)
```

```css
._dash-loading {
  margin: auto;
  color: transparent;
  width: 2rem;
  height: 2rem;
  text-align: center;
}

._dash-loading::after {
  content: '';
  display: inline-block;
  width: 2rem;
  height: 2rem;
  color: var(--bs-secondary);
  vertical-align: text-bottom;
  border: 0.25em solid currentColor;
  border-right-color: transparent;
  border-radius: 50%;
  -webkit-animation: spinner-border 0.75s linear infinite;
  animation: spinner-border 0.75s linear infinite;
  margin-top: 2rem;
}
```
