### ISSUE TITLE
dbc.Input does not behave like dcc.Input wrt `pattern` option

### ISSUE THREAD

**Issue by dagnic** [facultyai/dash-bootstrap-components#1045]
- dash                      2.17.0
- dash-bootstrap-components 1.6.0
- dash-core-components      2.0.0
- dash-html-components      2.0.0

### What is happening?

When `dcc.Input` content does not match the pattern, the border is coloured in red.
When `dbc.Input` content does not match the pattern, the border is NOT coloured in red.

### What should be happening?

When `dbc.Input` content does not match the pattern, the border should be coloured in red, as it is the case for `dcc.Input`  (out of the box, without the need to check the pattern in a callback and to set `valid`/`invalid` option accordingly).

This is especially true as the option description is identical for dcc and dbc.

> pattern (string; optional): A regular expression that the control's value is checked against. The pattern must match the entire value, not just some subset. Use the title attribute to describe the pattern to help the user. This attribute applies when the value of the type attribute is text, search, tel, url, email, or password, otherwise it is ignored. The regular expression language is the same as JavaScript RegExp algorithm, with the 'u' parameter that makes it treat the pattern as a sequence of unicode code points. The pattern is not surrounded by forward slashes.

### Code

```python
import dash
from dash import html
from dash.dependencies import Input
from dash import dcc
import dash_bootstrap_components as dbc


app = dash.Dash(__name__)

app.layout = html.Div(
    children=[
        dbc.Input(  # try to replace by dcc.Input
            id="myvalue",
            type="text",
            pattern=u"[a-z]{6}$",
        ),
    ]
)

@app.callback(
    [Input("myvalue", "value")]
)
def write_text(value):
        print(value)

if __name__ == "__main__":
    app.run_server(debug=True)

```

**Comment by tcbegley** [comment]
This is because dash-core-components applies some additional styling when the input is in an invalid state. You can achieve the same effect with some custom CSS. Put the following in a CSS file in your `assets/` folder

```css
input:invalid {
    outline: solid red;
}
```

or if you prefer a more Bootstrappy style you could do something like this

```css
input:invalid {
  border-color: #dc3545;
  padding-right: calc(1.5em + 0.75rem);
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 12 12' width='12' height='12' fill='none' stroke='%23dc3545'%3e%3ccircle cx='6' cy='6' r='4.5'/%3e%3cpath stroke-linejoin='round' d='M5.8 3.6h.4L6 6.5z'/%3e%3ccircle cx='6' cy='8.2' r='.6' fill='%23dc3545' stroke='none'/%3e%3c/svg%3e");
  background-repeat: no-repeat;
  background-position: right calc(0.375em + 0.1875rem) center;
  background-size: calc(0.75em + 0.375rem) calc(0.75em + 0.375rem);
  outline: none;
}

```
