### ISSUE TITLE
Bootstrap Style Matched Sliders

### ISSUE THREAD

**Issue by mmarras** [facultyai/dash-bootstrap-components#1050]
This is more a question than a feature request. 

#297 suggests, that Bootstrap themed sliders exist/existed. 

However, the question is how to apply the styling to the `dcc.Slider`? Bootstrap does not have a slider component, so it is comprehensible that it is not listed under components in the documentation. Then on the other hand, from a Dash viewpoint, it is arguably a rather central one.

So the feature request would be to either improve the documentation on how to give the sliders a matching style if this is already possible, or to create a `dbc.Slider` component. 

________

As a workaround for others potentially landing here, you can get the styling via a custom CSS: 

Place the below css file in to `assets/mycssfilename.css` to get the basic Bootstrap5 primary colorstyle.
```css
/* styles.css */

/* Customize the slider handle */
.rc-slider-handle {
    background-color: var(--bs-light); /* Handle color */
    border: 2px solid var(--bs-primary); /* Border color for the handle */
}
.rc-slider-handle:hover {
    border-color: var(--bs-primary);
}

.rc-slider-handle:active{
    border-color:var(--bs-primary);
    box-shadow: 0 0 5px var(--bs-primary);
}

/* Customize the slider track */
.rc-slider-track {
    background-color: var(--bs-primary); /* Track color */
}

.rc-slider-dot-active{
    border: 2px solid var(--bs-primary); /* Border color for the handle */
}

/* Customize the slider rail */
/* .rc-slider-rail { */
    /* background-color: var(--bs-light); Rail color */
/* }  */

.rc-slider-handle-click-focused:focus{
    border-color:var(--bs-primary);
}

```
