### ISSUE TITLE
Suggestion: RadioItems individual label styles

### ISSUE THREAD

**Issue by rolb** [facultyai/dash-bootstrap-components#222]
Hi,

First of all I'd like to thank you for creating this! Only just discovered this thanks to a suggestion on the plotly forums.

So I'd like to reproduce the following:
https://codepen.io/anon/pen/Bgozdj

The radio buttons or inputs are not displayed, I'm just using labels.

I'm currently using some hacky JS to achieve that result. I know almost no JS, so I was hoping to achieve this purely through Dash/callbacks.

Is it possible to add the PropTypes `labelCheckedStyle` and `labelUncheckedStyle`?
Alternatively, possibly easier, can you add a class like `.is-checked` for a checked label?

Thanks!

**Comment by tcbegley** [comment]
Hey @rolb, thanks for the suggestion.

I'll have a look at what we can do here. We have an open issue to support Bootstrap's custom inputs (#184) which may also help with this sort of thing, but I'll play around with your suggestions and see how it goes.

The specific thing you are trying to do though, you could already achieve with `dbc.ButtonGroup` and a callback. Check out the below example which produces this:

![image](https://user-images.githubusercontent.com/15220906/59548290-fe639d00-8f44-11e9-9073-cecb8995f5e1.png)

I would think that then overriding the styles of the underlying buttons should be easier than trying to modify radio buttons and so on, which I always found a bit messy.

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import Input, Output
from dash.exceptions import PreventUpdate

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = html.Div(
    [
        dbc.ButtonGroup(
            [
                dbc.Button("Day", id="day"),
                dbc.Button("Week", id="week"),
                dbc.Button("Month", id="month"),
            ]
        ),
        html.P(id="output", className="mt-3"),
    ],
    className="p-3",
)


# this callback uses dash.callback_context to figure out which button
# was clicked most recently. it then updates the "active" style of the
# buttons appropriately, and sets some output. it could be split into
# multiple callbacks if you prefer.
@app.callback(
    [
        Output("output", "children"),
        Output("day", "active"),
        Output("week", "active"),
        Output("month", "active"),
    ],
    [
        Input("day", "n_clicks"),
        Input("week", "n_clicks"),
        Input("month", "n_clicks"),
    ],
)
def toggle_buttons(n_day, n_week, n_month):
    ctx = dash.callback_context

    if not ctx.triggered:
        raise PreventUpdate
    else:
        button_id = ctx.triggered[0]['prop_id'].split('.')[0]

    if not any([n_day, n_week, n_month]):
        return "Nothing selected yet", False, False, False
    elif button_id == "day":
        return "Day is currently selected", True, False, False
    elif button_id == "week":
        return "Now week is selected", False, True, False
    elif button_id == "month":
        return "Look at that, month is selected", False, False, True


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by rolb** [comment]
Thanks so much @tcbegley! Played around with it and all looks good. I guess I'll need more Inputs then but that's a small compromise.

Also good to know that multiple Outputs are now supported, wasn't aware of that.

**Comment by happyshows** [comment]
Up, would love to see a neat implementation other than the button group with multi output approach...

**Comment by tcbegley** [comment]
Hey @rolb  and @happyshows 

Check out #238, I'm working on bringing custom radios and checkboxes to _dash-bootstrap-components_

You can try out the prerelease if you like

```
pip install dash-bootstrap-components==0.7.0rc2
```

I was able to use the new `RadioItems` component to recreate the above codepen example:

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.RadioItems(
            options=[
                {"label": "Day", "value": "day"},
                {"label": "Week", "value": "week"},
                {"label": "Month", "value": "month"},
            ],
            id="time-selector",
            labelClassName="date-group-labels",
            className="date-group-items",
            inline=True,
        ),
        html.P(id="output"),
    ],
    className="p-3",
)


@app.callback(Output("output", "children"), [Input("time-selector", "value")])
def return_value(value):
    return value


if __name__ == "__main__":
    app.run_server(debug=True)
```

```css
.custom-control-label::after,
.custom-control-label::before {
  display: none;
}

.custom-control {
  padding-left: 0;
}

.custom-control-inline {
  margin-right: 0;
}

.date-group-labels {
  border: 1px solid #ccc;
  border-radius: 0px;
  font: bold 11px Roboto, sans-serif;
  padding: 6px 7px;
  background-image: -webkit-linear-gradient(top, #fefefe, #f3f3f3);
  background-image: -moz-linear-gradient(top, #fefefe, #f3f3f3);
  cursor: pointer;
}

.custom-control-input:checked ~ .date-group-labels {
  background-image: -webkit-linear-gradient(top, #eee, #e3e3e3);
  background-image: -moz-linear-gradient(top, #eee, #e3e3e3);
  box-shadow: inset 0px 1px 2px rgba(0, 0, 0, 0.2);
}

.custom-radio:first-child .date-group-labels {
  border-radius: 3px 0 0 3px;
}

.custom-radio:last-child .date-group-labels {
  border-radius: 0 3px 3px 0;
}

.custom-radio:not(:last-child) .date-group-labels {
  border-right: none;
}

.date-group-labels:hover {
  box-shadow: inset 0px 1px 2px rgba(0, 0, 0, 0.2);
}
```

Which gives me this:

![giphy](https://user-images.githubusercontent.com/15220906/61533269-441ff380-aa24-11e9-9674-de6f2911abd0.gif)

If you get some time to try it out I'd love to hear feedback, I haven't extensively tested them yet.
