### ISSUE TITLE
Mark table row

### ISSUE THREAD

**Issue by Adrast** [facultyai/dash-bootstrap-components#237]
Is there an way to click and mark a row of a table? It's possible to do it with dash table, but they have an ugly pink color to the cell clicked.

**Comment by tcbegley** [comment]
Hey @Adrast 

You can't easily do this with our table since it's just a simple HTML table.

You can write some custom CSS to override the default pink colour of dash-table though. For example I just modified the simplest dash table example as follows:

```
.
├── app.py
└── assets
    └── style.css
```

```python
import dash
import dash_table
import pandas as pd

df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/solar.csv"
)

app = dash.Dash()

app.layout = dash_table.DataTable(
    id="table",
    columns=[{"name": i, "id": i} for i in df.columns],
    data=df.to_dict("records"),
    row_selectable="multi",
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

```css
/* style.css */
.dash-spreadsheet-container .dash-spreadsheet-inner table {
  --accent: blue;
  --selected-background: rgba(0, 100, 200, 0.3);
}
```

which gives me this sort of thing:

![image](https://user-images.githubusercontent.com/15220906/61472473-69f1bd80-a97c-11e9-8393-7ab714489884.png)

You could check #176 as well where there's a few links to what a more advanced table could look like. We'll probably never replicate all of the functionality of dash-table though.

**Comment by Adrast** [comment]
What version of dash/dash_table do you use. I can't seem to get your example to work. it doesn't change the colour of the selected cell.

**Comment by Adrast** [comment]
Wow, thanks! It works when I update the style.css file, but then changes back to hotpink on page reload. what am I missing out? btw do you know how to totally remove the selection when clicked on cell?

**Comment by tcbegley** [comment]
Hey @Adrast,

The first issue is probably because the `dash-table` CSS and your custom CSS have the same level of specificity, in which case the style that gets applied is whichever is defined second. Possibly reloading the page causes the custom CSS and the `dash-table` CSS to get loaded in a different order and hence change which style is applied. If this is the problem, you can fix it simply by writing a more specific CSS selector for your custom styles. For example you could wrap the layout of your app in an element with a particular class name, then refer to that in the CSS. So your Python code might now be something like this

```python
app.layout = html.Div(
    dash_table.DataTable(...),
    id="wrapper",
)
```

and your CSS something like this

```css
#wrapper .dash-spreadsheet-container .dash-spreadsheet-inner table {
  --accent: blue!important;
  --selected-background: rgba(0, 100, 200, 0.3)!important;
}
```

You can read more about specificity in the context of CSS selectors [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

The easiest way to not have the cell highlight when clicked on is probably just to set the border and background colours to the same as the default colours. I tried this quickly and it does the trick, but beware that there could be side effects that I didn't see.

```css
#wrapper .dash-spreadsheet-container .dash-spreadsheet-inner table {
  --accent: rgb(211, 211, 211);
  --selected-background: white !important;
}
```
