### ISSUE TITLE
Further enhancement on Radiobutton

### ISSUE THREAD

**Issue by happyshows** [facultyai/dash-bootstrap-components#241]
Firstly, thanks for implementing #222 . 

I feel the feature could be more useful if icons / custom images are allowed. Sometime we need image only radio options, sometimes we need image + text.

**Comment by tcbegley** [comment]
Hey @happyshows,

Thanks for raising this. Could you give an example of what you mean? I’ll look into whether I can either extend the functionality of the component or provide more examples.

**Comment by happyshows** [comment]
sure, [this](http://jsfiddle.net/La8wQ/10/) [that, ignore the fancy transformation piece](https://codepen.io/DavidBradbury/pen/HuCqx)

**Comment by tcbegley** [comment]
Cool thanks. I'll take a look at how best to do this with _dash-bootstrap-components_. It's very likely we won't support this entirely natively through the components, since the focus of the library is providing functionality of Bootstrap, however I will at least try to provide some examples for how you can achieve this kind of thing, and extend the components to make it easier if necessary.

**Comment by dgasmith** [comment]
Is forming the radio items like a button group possible, an example is [here](https://mdbootstrap.com/snippets/jquery/mdbootstrap/921368). The main drawback it seems it that the radio items are organized with input/label in the same div rather than being able to place the input inside the label.

**Comment by tcbegley** [comment]
Hey @dgasmith, the simplest way to achieve this is with a `ButtonGroup` and a callback. Something like this:

```python
import dash
import dash_bootstrap_components as dbc
from dash.dependencies import Input, Output

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.ButtonGroup(
    [
        dbc.Button("Button 1", id="button-1"),
        dbc.Button("Button 2", id="button-2"),
        dbc.Button("Button 3", id="button-3"),
    ]
)


@app.callback(
    [Output(f"button-{i}", "active") for i in [1, 2, 3]],
    [Input(f"button-{i}", "n_clicks") for i in [1, 2, 3]],
)
def set_active(n1, n2, n3):
    if any([n1, n2, n3]):
        # only do this if at least one of the buttons has been clicked

        # figure out which button was clicked
        ctx = dash.callback_context
        button_id = ctx.triggered[0]["prop_id"].split(".")[0]

        return [button_id == f"button-{i}" for i in [1, 2, 3]]

    return False, False, False


if __name__ == "__main__":
    app.run_server(debug=True)
```

If you know a bit of JavaScript you could even write a clientside callback to achieve the same without having to ping the server.

**Comment by dgasmith** [comment]
Thanks! I had looking into the multiple I/O idea, but we need ~15 of these all told so it is pretty unwieldy. The loops do help some however!

Two quick questions:
1) I think I can probably figure out the JS, but do know of anyone who has implemented this?
2) Is it possible/advisable to add this kind of ButtonGroup to this repo?

PS: Doesn't `n_clicks` increment on click so having a user deselect a button group cause problems in this setting?

**Comment by tcbegley** [comment]
1. I actually thought about this again and I'm not sure that an equivalent of `dash.callback_context` is available for clientside callbacks...
2. I'm not quite sure how to capture this logic in the component, but I can think about it.

> PS: Doesn't n_clicks increment on click so having a user deselect a button group cause problems in this setting?

Normally clicking on a radio button doesn't deselect that option, so it depends on the behaviour you are expecting? The example I posted will always just set the last clicked button to active.

Anyway, if you would rather avoid writing callbacks, here's an alternative that uses a bit of CSS hackery to restyle the `RadioItems` component. It's probably a better way of doing it on balance:

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.RadioItems(
            id="radios",
            className="btn-group",
            labelClassName="btn btn-secondary",
            labelCheckedClassName="active",
            options=[
                {"label": "Option 1", "value": 1},
                {"label": "Option 2", "value": 2},
                {"label": "Option 3", "value": 3},
            ],
            value=1,
        ),
        html.Div(id="output"),
    ],
    className="p-5 radio-group",
)


@app.callback(Output("output", "children"), [Input("radios", "value")])
def foo(value):
    return f"Selected value: {value}"


if __name__ == "__main__":
    app.run_server(debug=True)
```

include the following CSS in `assets/style.css` or similar.

```css
/* Turn off existing buttons */
.radio-group .custom-control-input ~ .custom-control-label::before {
	content: none;
}

.radio-group .custom-radio .custom-control-input ~ .custom-control-label::after {
	content: none;
}

/* restyle radio items */
.radio-group .custom-control {
	padding-left: 0;
}

.radio-group .btn-group > .custom-control:not(:first-child) > .btn {
	margin-left: -1px;
}

.radio-group .btn-group > .custom-control:not(:last-child) > .btn {
	border-top-right-radius: 0;
	border-bottom-right-radius: 0;
}

.radio-group .btn-group > .custom-control:not(:first-child) > .btn {
	border-top-left-radius: 0;
	border-bottom-left-radius: 0;
}
```
