### ISSUE TITLE
RadioItems style change when set id 

### ISSUE THREAD

**Issue by gungui98** [facultyai/dash-bootstrap-components#456]
dash==1.16.0
dash-bootstrap-components==0.10.6
dash-core-components==1.12.0

- components affected by bug:
RadioItems

### What is happening?

I am trying to restyle the RadioItems into star rating, the styling works fine until I set id for RadioItems, the style change into unexpected.

### What should be happening?

I want the component keep the same styling when I set id for later callback

### Code

```python

import dash
import dash_bootstrap_components as dbc
import dash_html_components as html

FONT_AWESOME = "https://use.fontawesome.com/releases/v5.10.2/css/all.css"
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP, FONT_AWESOME],
                suppress_callback_exceptions=True)



app.layout = html.Div([
    dbc.RadioItems(
        options=[
            {'label': '', 'value': '1'},
            {'label': '', 'value': '2'},
            {'label': '', 'value': '3'},
            {'label': '', 'value': '4'},
            {'label': '', 'value': '5'},
        ],
        value='5',
        # labelStyle={'display': 'inline-block'},
        className="star-rating",
        labelClassName="fa fa-star",
        inline=True,
        # id="rating-star",
    )
])


if __name__ == '__main__':
    app.run_server(debug=True)
```
my css code

```css

.star-rating {
    direction: rtl;
    display: inline-block;
    padding: 20px
}

.star-rating input[type=radio] {
    display: none
}

.star-rating .form-check {
    color: #bbb;
    font-size: 18px;
    padding: 0;
    cursor: pointer;
    -webkit-transition: all .3s ease-in-out;
    transition: all .3s ease-in-out
}
.star-rating .form-check {
    color: #bbb;
    font-size: 18px;
    padding: 0;
    cursor: pointer;
    -webkit-transition: all .3s ease-in-out;
    transition: all .3s ease-in-out
}

.star-rating .form-check:hover ~ .form-check {
    color: #f2b600
} 

```
