### ISSUE TITLE
Tab.label type 

### ISSUE THREAD

**Issue by sean898** [facultyai/dash-bootstrap-components#478]
I propose changing the `dbc.Tab` `label` property to accept *a list or a singular dash component*, in addition to the current argument type of *string*. 

This would enable developers to craft more advanced tabbed-displays, which could include: 
- A dynamic counter of elements available within the tab's `children` view using the `dbc.Badge` component
- Font Awesome icons in the tab's label using the `html.I` component

**Comment by tcbegley** [comment]
Hi @sean898 

I would add this if I could, but because of the way dash-renderer works means only the `children` prop can receive other components as arguments. Unfortunately unless that changes, this one is out of our hands.

That said, here's a workaround for FontAwesome icons using a little CSS hackery

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html

FA = "https://use.fontawesome.com/releases/v5.15.1/css/all.css"

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP, FA])

app.layout = dbc.Container(
    dbc.Tabs(
        [
            dbc.Tab(
                html.Div("This is the content of tab 1", className="p-4"),
                label="Tab 1",
            ),
            dbc.Tab(
                html.Div("This is the content of tab 2", className="p-4"),
                label="Tab 2",
            ),
        ],
        id="tabs",
    ),
    className="p-5",
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

and in `assets/style.css`

```css
#tabs .nav-item .nav-link::after {
  font-family: "Font Awesome 5 Free";
  font-weight: 200;
  font-style: normal;
  margin: 0px 0px 0px 10px;
  text-decoration: none;
}

#tabs .nav-item:nth-child(1) .nav-link::after {
  content: "\f005";
}

#tabs .nav-item:nth-child(2) .nav-link::after {
  content: "\f2bd";
}
```

The `:nth-child` selector is a little brittle, but it will do the job. You should see something like this

![image](https://user-images.githubusercontent.com/15220906/100156984-c2569a80-2ea1-11eb-8979-a1d580755009.png)
