### ISSUE TITLE
Style problems with RadioItems as ButtonGroup

### ISSUE THREAD

**Issue by sambaPython24** [facultyai/dash-bootstrap-components#650]
Hello, I would like to use the [RadioItems as ButtonGroup](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/button_group/). 

When not changing the CSS style 
```CSS
/* Turn off existing buttons */
.radio-group .custom-control-input ~ .custom-control-label::before {
  content: none;
}
```
the circular radio buttons do not vanish. 

As I am not familiar with how to change the general CSS style file , I would like 
to ask you, wether it is possible to provide a **style-dict** that can be given to the widget locally. 

That means, I would like to have a style dict to put into the ```dbc.RadioItems``` directly.
