### ISSUE TITLE
Modal with backdrop=False still does not allow through click events

### ISSUE THREAD

**Issue by JonThom** [facultyai/dash-bootstrap-components#758]
- dash version: `#2.0.0`
- dash-bootstrap-components version: `#1.0.0`
- components affected by bug: Modal

### What is happening?

With dbc.Modal, setting backdrop=False (or using `backdrop_class_name` to remove the backdrop) still leaves the shell div (.modal) that is used under the hood to position the modal. This means that pointer events outside the Modal still do not get through.

### What should be happening?

I expected to be able to use `backdrop=False` to remove the backdrop, allowing mouse interaction with other elements outside the actual Modal.

### Code

This can be fixed by changing the `.modal` `pointer-events` CSS property:

```css
.modal {
    // allow clicks to pass through for custom click handling to close modal
    pointer-events: none !important;
}
```
