### ISSUE TITLE
Can title of AccordionItem be a component, not only a String?

### ISSUE THREAD

**Issue by xianhu** [facultyai/dash-bootstrap-components#769]
The title property of AccordionItem only be a string format, can it be a component? I want to add a icon before title text.

**Comment by tcbegley** [comment]
Hi @xianhu 

It's not possible to pass components to any prop other than `children` unfortunately, this is a limitation of Dash itself.

However, it is still possible to do what you want based on [this answer](https://github.com/facultyai/dash-bootstrap-components/issues/478). The idea is to use some custom CSS to carefully target the accordion headers and insert an icon.

Check out the following example

```
.
├── app.py
└── assets
    └── style.css
```

```python
# app.py
import dash_bootstrap_components as dbc
from dash import Dash, html

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP, dbc.icons.FONT_AWESOME])

app.layout = dbc.Container(
    dbc.Accordion(
        [
            dbc.AccordionItem(
                [
                    html.P("This is the content of the first section"),
                    dbc.Button("Click here"),
                ],
                title="Item 1",
            ),
            dbc.AccordionItem(
                [
                    html.P("This is the content of the second section"),
                    dbc.Button("Don't click me!", color="danger"),
                ],
                title="Item 2",
            ),
            dbc.AccordionItem(
                "This is the content of the third section", title="Item 3",
            ),
        ],
        id="my-accordion",
    ),
    class_name="p-5",
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

```css
/* assets/style.css */
#my-accordion .accordion-item .accordion-button::before {
  font-family: "Font Awesome 5 Free";
  font-weight: 200;
  font-style: normal;
  margin: 0px 10px 0px 0px;
  text-decoration: none;
}

#my-accordion .accordion-item:nth-child(1) .accordion-button::before {
  content: "\f005";
}

#my-accordion .accordion-item:nth-child(2) .accordion-button::before {
  content: "\f2bd";
}

#my-accordion .accordion-item:nth-child(3) .accordion-button::before {
  content: "\f151";
}
```

Which produces something like this.

![image](https://user-images.githubusercontent.com/15220906/141674051-7f2a2867-b666-4a0c-8d7b-5907495a226c.png)
