### ISSUE TITLE
dbc.FormFeedback not working with type="number" dbc.Input

### ISSUE THREAD

**Issue by raisaat08** [facultyai/dash-bootstrap-components#929]
- dash version: `2.71`
- dash-bootstrap-components version: `1.2.1`
- components affected by bug: `dbc.Input(type="number")`, `dbc.FormFeedback`

### What is happening?

`dbc.FormFeedback` does not seem to work when used with number inputs. I am not getting any feedback message.

### What should be happening?

I want `dbc.FormFeedback` to display a feedback message when the number entered in `dbc.Input(type="number")` is out of range.

### Code

`html.Div` element with `dbc.Input(type="number")` and `dbc.FormFeedback`:
```
html.Div([
    dbc.Input(type="number", value=3, min=1, max=5, step=1, id='some-number'),
    dbc.FormFeedback(
        "Please enter a number between 1 and 5 (inclusive).",
        type="invalid",
        id='some-number-feedback'
    )
])
```

This is my dash callback function for the input:
```
@app.callback(
    Output('some-number', "valid"),
    Output('some-number', "invalid"),

    Input('some-number', "value"),
)
def check_validity(num):
    if val:
        in_range = num >= 1 and num <= 5
        return in_range, not in_range
    return False, False
```

**Comment by tcbegley** [comment]
Hi @raisaat08 

The reason this is not working is that the `Input` sends the value `None` to the callback if it's out of range. This is by design to mimic the behaviour of `dcc.Input`.

I think you have two options:

1. You could simply set `invalid=True` whenever `num is None` in your callback.

2. You could add some CSS to make the feedback display when the input is in an invalid state (no callback needed in this case!

```python
import dash_bootstrap_components as dbc
from dash import Dash

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Input(
            type="number", value=3, min=1, max=5, step=1, id="some-number"
        ),
        dbc.FormFeedback(
            "Please enter a number between 1 and 5 (inclusive).",
            type="invalid",
            id="some-number-feedback",
        ),
    ],
    class_name="p-5",
)


if __name__ == "__main__":
    app.run_server(debug=True)
```

```css
input:invalid ~ .invalid-feedback {
  display: block;
}

input:invalid {
  border-color: #dc3545;
  padding-right: calc(1.5em + 0.75rem);
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 12 12' width='12' height='12' fill='none' stroke='%23dc3545'%3e%3ccircle cx='6' cy='6' r='4.5'/%3e%3cpath stroke-linejoin='round' d='M5.8 3.6h.4L6 6.5z'/%3e%3ccircle cx='6' cy='8.2' r='.6' fill='%23dc3545' stroke='none'/%3e%3c/svg%3e");
  background-repeat: no-repeat;
  background-position: right calc(0.375em + 0.1875rem) center;
  background-size: calc(0.75em + 0.375rem) calc(0.75em + 0.375rem);
  outline: none;
}
```
