### ISSUE TITLE
dbc.Tabs not showing all tabs in expanded mode in 1.4.1

### ISSUE THREAD

**Issue by seanslma** [facultyai/dash-bootstrap-components#957]
Before opening:

- [Search for duplicate or closed issues](https://github.com/facultyai/dash-bootstrap-components/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/facultyai/dash-bootstrap-components/blob/main/.github/CONTRIBUTING.md)

Please fill out the below information as much as possible.

- dash version: `2.9.3`
- dash-bootstrap-components version: `1.4.1`
- components affected by bug: dbc.Tabs

### What is happening?

Multiple tabs when they are expanded vertically, only the activate tab is visible in 1.4.1.

### What should be happening?

Multiple tabs when they are expanded, should all be visible vertically, but only the activate tab is visible in the expanded mode in 1.4.1.

In 1.0.3, all works as expected.

### Code

```python
tab_a = html.Div([
    html.Div(
        'Tab-a', 
        className='tab-title'
    ),
    dcc.Loading(
        id='loading-a-graph',
        type="default",
        color='#5e6b73',
    )
], className='graph-tab-content h-100')

tab_b = html.Div([
    html.Div(
        'Tab-b', 
        className='tab-title'
    ),
    dcc.Loading(
        id='loading-b-graph',
        type="default",
        color='#5e6b73',
    )
], className='graph-tab-content h-100')

tabs = dbc.Tabs(
    [
        dbc.Tab(tab_a, label="Tab-a", id='a-tab'),
        dbc.Tab(tab_b, label="Tab-b", id='b-tab'),
    ],
    className="white-background"
)

forecast_graphs = html.Div([
    html.Div([
        dbc.Card([
            dbc.CardBody([
                html.Div([
                    html.A([
                        html.Span("Show all graphs", id='show-more-text', className='me-1'), 
                        html.I(className="fa fa-angle-up show-more-arrow", id='show-more-arrow')
                    ], id="show-more", className="show-more-btn")
                ], className="show-more"),
                html.Div(
                    tabs,
                    style={"height": "100%"},
                    id='graphs-container',
                    className='forecast-graphs-container'
                )
            ])
        ], className='forecast-graphs-wrapper h-100', style={'padding': '0', 'border': 'none'})
    ], className="overlay-content h-100")
], className="overlay", id="overlay")
```

```css
.overlay {
  height: 33%;
  width: 100%;
  position: absolute;
  z-index: 1000;
  left: 0;
  bottom: 0;
  background-color: black;
  background-color: rgba(255, 255, 255, 0.9);
  overflow-x: hidden;
  transition: 0.5s; }
  .overlay.expanded {
    height: 100%; }
    .overlay.expanded .forecast-graphs-container .tab-title {
      display: block; }
    .overlay.expanded .show-more {
      padding: 5px 0; }
    .overlay.expanded .show-more-arrow {
      transform: rotate(180deg); }
    .overlay.expanded .forecast-graphs-container {
      margin: 0 !important; }
    .overlay.expanded .nav-tabs {
      display: none !important; }
    .overlay.expanded .tab-pane {
      display: block !important; }
    .overlay.expanded .tab-content {
      border: 1px solid #cfd3d6;
      border-radius: .25rem; }
```
